### ISSUE TITLE
Consider all files `db.*` as zone files

### ISSUE THREAD

**Issue by penguineer** [FreifunkMD/dns-test-repo#1]

**Comment by 24367dfa** [comment]
seems suitable

Should we assume, that the repo contains only one zone file? Otherwise generating a single serial might update the serial for records that have not actually been changed.

**Comment by penguineer** [comment]
That's a good question. 

In theory there can be multiple zone files, however, right now there is also a configuration that must list the zones and contains only one file.

Our two use cases `ffmd` and `md.freifunk.net` also contain only one zone file (also does not make sense to merge them into one container).

So far, only one zone file is used.

**Comment by penguineer** [comment]
Maybe we have an extra check that makes sure that there is only one zone file and that it is mentioned in the configuration?

This would serve two purposes:
1. Check that CI and repository structure match
2. Verify the configuration file

Could also be two actions that are called in parallel.

**Comment by christf** [comment]
personally I think we should build complexity in the tooling when we need it to support the configuration. Once the need arises, the tooling can be adjusted to support multiple config files per repo - or we can just create another repo - whichever works best then.
Of course building a check would be helpful to avoid user errors.
